#!/usr/bin env bash
# What type of netwrok a computer in local is connected to?
3
# What type of network could connect an office in one building to another office in a building a few streets away?
2
# What network do you use when you browse from your smartphone?
1
