#!/usr/bin/env bash
# A bash script that pings an IP address passed as an argument:
#  Accepts a string as an argument
#  Displays "usage: 5-is_the_host_on_the_network {IP_ADDRESS}" if no argument is passed
#  Ping the IP 5 times

if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$  ]]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
