#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond process.
# Do not use "kill" or "killall" command

# Terminate the infinite process
pkill -15 "bash ./4-to_infinity_and_beyond" -f
