#!/usr/bin/env bash
# A loop that displays:
#  "bad luck" for the 4 iteration
#  "good luck" for the 8 iteration
#  "Best School" for the rest of the loop

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then	
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
