#!/usr/bin/env bash
# A bash script that displays:
#  "4" then "bad luck from china" on the 4th iteration
#  "9" then "bad luck from japan" on the 9th iteration
#  "17" then "bad luck from italy" on the 17th iteration

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
