#!/usr/bin/env bash
# Bash script that displays current directory in a list format
# Only display part of the name after the first dash is displayed

list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
